### ISSUE TITLE
Backport Addon

### ISSUE THREAD

**Issue by Redledr** [MarioCatuogno/PanzaUI#20]
Afternoon! I frequent r/wowui subreddit, I saw your UI and absolutely fell in love with it. Is there a WoW Cataclysm version on the backburner? Also is your WA imports usable on the WoW Cataclysm version or is this retail only? Thanks, have an awesome day!!

**Comment by MarioCatuogno** [comment]
Hello @Redledr! Welcome :)
Unfortunately, actually, I don't have so much time to play and try also WOW Classic. The Utilities WA ([Link](https://github.com/MarioCatuogno/PanzaUI/blob/main/WeakAuras/PanzaUI-Utilities.txt)) should work also in Classic, but the classes WA are only for Retail.

If in the near future I will find more time, I will try to test and adapt the UI also for WOW Cataclysm!
