### ISSUE TITLE
Some differencies on profile imports, and some not working

### ISSUE THREAD

**Issue by Dieman89** [MarioCatuogno/PanzaUI#21]
Blizzard UI Looks different after import:
![image](https://github.com/MarioCatuogno/PanzaUI/assets/28837891/40020468-40d2-4925-9323-a8ee3280f2b2)
 
ThreadPlates:
![image](https://github.com/MarioCatuogno/PanzaUI/assets/28837891/6aab9e9c-1e23-4c09-8151-bd9a02af4b37)

And SUF also looks different from what you have:

![image](https://github.com/MarioCatuogno/PanzaUI/assets/28837891/707d05dd-e1f3-4d3d-ae1a-35967d1f08d9)

**Comment by MarioCatuogno** [comment]
Hi @Dieman89! 
Thanks for coming here! Few question to better address the issue:
- are you using Threat Plates last version (actually 11.2.8)?
- can you try to use [this](https://raw.githubusercontent.com/MarioCatuogno/PanzaUI/0.7.0-RELEASE/Profiles/PanzaUI-DpsTank.txt) version of the PanzaUI profile for Blizzard UI and tell me if you still have problems?
- can you try to use [this](https://raw.githubusercontent.com/MarioCatuogno/PanzaUI/0.7.0-RELEASE/Profiles/PanzaUI-SUF.txt) version of SUF profile and tell me if you still have problems?
- are you using other addons?

**Comment by MarioCatuogno** [comment]
Hi @Dieman89,
I've just release a new version of PanzaUI. Can you try it downloading from [here](https://github.com/MarioCatuogno/PanzaUI/releases/tag/0.7.0)? Let me know if now it's working!

Thanks
