### ISSUE TITLE
Action bar issues - error.

### ISSUE THREAD

**Issue by PrintNewLine** [MarioCatuogno/PanzaUI#27]
Hi

During the installation I've faced few issues regarding UI.

1. Cannot move action bars, as I am getting bug.

`141x ...izzard_EditMode/Mainline/EditModeSystemTemplates.lua:535: attempt to perform arithmetic on local 'left' (a nil value)
[string "@Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua"]:535: in function `GetScaledSelectionSides'
[string "@Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua"]:507: in function `IsVerticallyAlignedWithFrame'
[string "@Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua"]:725: in function `GetFrameMagneticEligibility'
[string "@Blizzard_EditMode/Mainline/EditModeUtil.lua"]:147: in function `GetEligibleMagneticFrames'
[string "@Blizzard_EditMode/Mainline/EditModeUtil.lua"]:336: in function `GetMagneticFrameInfoOptions'
[string "@Blizzard_EditMode/Mainline/EditModeUtil.lua"]:419: in function `GetMagneticFrameInfos'
[string "@Blizzard_EditMode/Mainline/EditModeManager.lua"]:1061: in function `RefreshSnapPreviewLines'
[string "@Blizzard_EditMode/Mainline/EditModeManager.lua"]:170: in function <...ddOns/Blizzard_EditMode/Mainline/EditModeManager.lua:168>

Locals:
self = BossTargetFrameContainer {
 0 = <userdata>
 UpdateMagnetismRegistration = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:731
 GetSnapOffsets = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:609
 systemInfo = <table> {
 }
 IsFrameAnchoredToMe = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:694
 TrySetCompositeNumberSettingValue = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:212
 downKeys = <table> {
 }
 GetFixedSize = <function> defined @Blizzard_SharedXML/LayoutFrame.lua:156
 breakSnappedFramesOnSave = true
 GetFixedWidth = <function> defined @Blizzard_SharedXML/LayoutFrame.lua:148
 LayoutChildren = <function> defined @Blizzard_SharedXML/LayoutFrame.lua:245
 GetSelectionOffset = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:540
 ResetToDefaultPosition = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:254
 GetScaledSelectionSides = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:532
 SelectSystem = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:763
 SetFixedWidth = <function> defined @Blizzard_SharedXML/LayoutFrame.lua:135
 GetFrameMagneticEligibility = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:714
 UpdateSystemSettingUseLargerFrame = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:1223
 CalculateFrameSize = <function> defined @Blizzard_SharedXML/LayoutFrame.lua:210
 AddLayoutChildren = <function> defined @Blizzard_SharedXML/LayoutFrame.lua:55
 smallSize = true
 IsBelowFrame = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:499
 spacing = 10
 SetFixedSize = <function> defined @Blizzard_SharedXML/LayoutFrame.lua:143
 HasActiveChanges = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:381
 GetScaledCenter = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:525
 SetCastBarPosition = <function> defined @Blizzard_UnitFrame/TargetFrame.lua:1366
 DoesSettingDisplayValueEqual = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:445
 UpdateDisplayInfoOptions = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:456
 GetSystemName = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:822
 ProcessMovementKey = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:39
 GetSettingValueBool = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:436
 HasCompositeNumberSetting = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:385
 alwaysUseTopRightAnchor = true
 IsLayoutFrame = <function> defined @Blizzard_SharedXML/LayoutFrame.lua:36
 DoesSettingValueEqual = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:440
 MarkDirty = <function> defined @Blizzard_SharedXML/LayoutFrame.lua:99
 ShouldResetSettingsDialogAnchors = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:1105
 GetChildPadding = <function> defined @Blizzard_SharedXML/LayoutFrame.lua:187
 dirtySettings = <table> {
 }
 isManagedFrame = true
 IsToTheLeftOfFrame = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:481
 GetSettingsDialogAnchor = <function> defined @Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:465
 hasActiveChanges `

I can imagine that might be connected with 3440x1440 resolution, yet I cannot move action bars nor any other UI parts from blizzard. Installation went step by step via github.

Kind Regards,
Dave

**Comment by MarioCatuogno** [comment]
Hi @PrintNewLine, thanks for trying the UI!
Few questions before trying to reproduce the problem:

1. have you set the "Snap to Grid" option in Edit Mode? If yes, can you disable it and see if it's working?
2. have you other addons installed apart from PanzaUI, SUF, Raid Frame Settings, Hide Main Menu Bar and WeakAuras?
3. at what resolution are you playing?

Thanks!
Mario

**Comment by MarioCatuogno** [comment]
Hi @PrintNewLine ,
I've just release a new version of PanzaUI. Can you try it downloading from [here](https://github.com/MarioCatuogno/PanzaUI/releases/tag/0.7.0)? Let me know if now it's working!

Thanks

**Comment by PrintNewLine** [comment]
Hello

I've cleared everything and installed new release of UI. Works as a charm. I do work and play on 3440x1440 resolution.

Thank you for the release,
Dave

**Comment by PrintNewLine** [comment]
Yet one question - how to make action bars visible? Id like to see them during the fight and being idle.

Thanks,
Dave

**Comment by MarioCatuogno** [comment]
> Yet one question - how to make action bars visible? Id like to see them during the fight and being idle.
> 
> Thanks, Dave

You can re-enable the Main Action Bar in add-on "Hide My Main Bar" and enable all others action bars with the standard Blizzard Edit Mode.
