### ISSUE TITLE
No menu / Portrait error. 

### ISSUE THREAD

**Issue by PandaRedd** [MarioCatuogno/PanzaUI#43]
Decided to try this again after a couple of patches of not using it. Clean install of WoW. There's no config option under addon settings, and /panzaui doesn't do anything. 

Pretty sure it's related to this LUA error:

`1x PanzaUI/options.lua:13: attempt to index global 'configPanel' (a nil value)
[string "@PanzaUI/options.lua"]:13: in main chunk

Locals:
_ = "PanzaUI"
addonTable = <table> {
 core = <table> {
 }
 panel = PanzaUIOptions {
 }
}
createCheckbox = <function> defined @PanzaUI/options.lua:3
addonTitle = "PanzaUI"
addonVersion = "|cff00FF98Panza|rUI"
(*temporary) = nil
(*temporary) = "|cff00FF98Panza|rUI"
(*temporary) = "World of Warcraft UI"
(*temporary) = true
(*temporary) = ""
(*temporary) = "INSECURE"
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'configPanel' (a nil value)"`

Also the player and target 2d portrait weakauras are throwing LUA errors and not loading.

**Comment by MarioCatuogno** [comment]
Hi @PandaRedd,
thanks for trying the UI! Have you downloaded and installed the last version ([v.0.7.1](https://github.com/MarioCatuogno/PanzaUI/releases/tag/0.7.1)) following [this](https://github.com/MarioCatuogno/PanzaUI/blob/main/HOW_TO_INSTALL.md) guide?

I had to change many things after TWW pre-patch and at the moment the in-game menu is disabled, but everything should work just fine!

**Comment by MarioCatuogno** [comment]
Hi @PandaRedd, have you had the chance to try with the latest version of the UI?

**Comment by PandaRedd** [comment]
Yes thank you. Portraits are working. :) Is there a way to manually disable the buff hiding while the in-game menu is still disabled? :)

**Comment by MarioCatuogno** [comment]
@PandaRedd You mean the auto-collapse function?

<img width="487" alt="image" src="https://github.com/user-attachments/assets/ea750076-5a9f-4a7f-83c1-0ff624de69b5">

If yes, you have to manually remove the code in the `core.lua` file of the PanzaUI addon, specifically this part:

<img width="630" alt="image" src="https://github.com/user-attachments/assets/797bdbc4-6179-4481-a581-ae5f1b05bb93">

Let me know if you need any help!

**Comment by PandaRedd** [comment]
Thank you. Works perfectly now. :) This is such a great UI.

**Comment by MarioCatuogno** [comment]
> Thank you. Works perfectly now. :) This is such a great UI.

Great! I'm glad you like it! If you have advice/suggestion to improve the UI let me know! Enjoy the game :)
