### ISSUE TITLE
Request: Priest weakauras's (all specs)

### ISSUE THREAD

**Issue by maikelschippers** [MarioCatuogno/PanzaUI#53]
Request: Priest weakauras's (all specs)

**Comment by MarioCatuogno** [comment]
Hi @maikelschippers,
I'm not actively playing Priest (I have an Holy priest levelled during MoP:Remix) but I will start to work on a  first WA for Holy spec next week!

Connected to #38

**Comment by MarioCatuogno** [comment]
Hi @maikelschippers,
just released version [0.8.2](https://github.com/MarioCatuogno/PanzaUI/releases/tag/0.8.2) with Holy Priest spec. For the moment I will not release other Priest specs as I'm not actively playing it, but let me know if everything is working fine with the Holy Priest aura!
